### ISSUE TITLE
wp10 model has prediction weight in B and C class with blank pages

### ISSUE THREAD

**Issue by halfak** [wiki-ai/revscoring#133]
e.g. http://ores.wmflabs.org/scores/enwiki/wp10/671913880/

**Comment by halfak** [comment]
New model does a little bit better:

```
revscoring score models/enwiki.wp10.rf.model 671913880 --api=https://en.wikipedia.org/w/api.php
Sending requests with default User-Agent.  Set 'user_agent' on api.Session to quiet this message.
671913880	{"probability": {"Start": 0.1298195791901315, "FA": 0.004256495744929551, "GA": 1.5377565362341574e-06, "Stub": 0.6444542822462371, "B": 0.10040774584993681, "C": 0.1210603592122288}, "prediction": "Stub"}
```

Maybe we need some blank observations so that the RF can account for that.  What do you think @nettrom?

**Comment by nettrom** [comment]
If I remember correctly, stubs are rather straightforward to determine by length alone, as their length is significantly shorter than other types of articles.  Somehow haven't got my length-by-quality-class graph easily available, but I'll dig it up (I could also create a new one).

So what I'm thinking is adding say 500 revisions that are obviously stubs due to their short length, and see if that improves the scoring, as I think adding 500 0-length revisions might train a model that is less practically aligned.

**Comment by ragesoss** [comment]
One approach might be to add a new prediction class to the model, something like 'not an article' or 'deleted', and train this on revisions where the page gets deleted. We know that there should basically be an asymptote for zero-length pages: those are not even stubs, and they get deleted. There's a liminal area of "sub-stubs" that might go either way when users come along to evaluate them: they could end up classified as stubs, or they could get marked for deletion and removed.

Something where the model doesn't assume that a revision even meets the minimum threshold of "stub" quality would make it much more useful for purposes beyond just estimating the quality of pages that have already gone through the minimum vetting of having survived as live Wikipedia articles.

**Comment by halfak** [comment]
Looks like this isn't really a big problem anymore.  

See https://ores.wmflabs.org/v2/scores/enwiki/wp10/754010401?datasource.revision.text=%22%22

It looks like the wp10 model now puts most of the weight into Stub and Start -- which is decidedly less crazy.
